version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
