version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.working
    ports:
      - "80:80"
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
