version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Если у вас есть backend
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
