version: '3.8'

services:
  simple-server:
    image: python:3.9-alpine
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    working_dir: /app
    volumes:
      - ./test-page:/app
    restart: unless-stopped
